--1) run this
-- 
/*
SELECT 'SELECT ''' || name || ''' AS TableName, COUNT(*) AS RecordCount FROM ' || name || ' union all ' 
FROM sqlite_master 
WHERE type='table';
-- */

--2)
--	copy all the rows from the above
--	paste them between the parentheses below (replacing whatever is there)
--	delete the "union all" from the end of the last line
--	run the query (everything between the /* and the */)

-- /*
select * FROM
(
	SELECT 'DIM_CompanyNames' AS TableName, COUNT(*) AS RecordCount FROM DIM_CompanyNames union all 
SELECT 'sqlite_sequence' AS TableName, COUNT(*) AS RecordCount FROM sqlite_sequence union all 
SELECT 'DIM_Condition' AS TableName, COUNT(*) AS RecordCount FROM DIM_Condition union all 
SELECT 'DIM_NamingTheme' AS TableName, COUNT(*) AS RecordCount FROM DIM_NamingTheme union all 
SELECT 'DIM_PopPoliticalStatus' AS TableName, COUNT(*) AS RecordCount FROM DIM_PopPoliticalStatus union all 
SELECT 'DIM_ShipyardCompanies' AS TableName, COUNT(*) AS RecordCount FROM DIM_ShipyardCompanies union all 
SELECT 'DIM_WealthUse' AS TableName, COUNT(*) AS RecordCount FROM DIM_WealthUse union all 
SELECT 'FGNicknames' AS TableName, COUNT(*) AS RecordCount FROM FGNicknames union all 
SELECT 'ForeignAid' AS TableName, COUNT(*) AS RecordCount FROM ForeignAid union all 
SELECT 'GovType' AS TableName, COUNT(*) AS RecordCount FROM GovType union all 
SELECT 'FCT_HullDescription' AS TableName, COUNT(*) AS RecordCount FROM FCT_HullDescription union all 
SELECT 'FCT_Increments' AS TableName, COUNT(*) AS RecordCount FROM FCT_Increments union all 
SELECT 'FCT_KnownRuinRace' AS TableName, COUNT(*) AS RecordCount FROM FCT_KnownRuinRace union all 
SELECT 'DIM_LineNames' AS TableName, COUNT(*) AS RecordCount FROM DIM_LineNames union all 
SELECT 'DIM_MiningNames' AS TableName, COUNT(*) AS RecordCount FROM DIM_MiningNames union all 
SELECT 'PhoneticNames' AS TableName, COUNT(*) AS RecordCount FROM PhoneticNames union all 
SELECT 'FCT_PopMDChanges' AS TableName, COUNT(*) AS RecordCount FROM FCT_PopMDChanges union all 
SELECT 'RaceCompare' AS TableName, COUNT(*) AS RecordCount FROM RaceCompare union all 
SELECT 'FCT_JumpPoint' AS TableName, COUNT(*) AS RecordCount FROM FCT_JumpPoint union all 
SELECT 'DIM_SetAtmosphere' AS TableName, COUNT(*) AS RecordCount FROM DIM_SetAtmosphere union all 
SELECT 'DIM_TraitGroup' AS TableName, COUNT(*) AS RecordCount FROM DIM_TraitGroup union all 
SELECT 'Wormholes' AS TableName, COUNT(*) AS RecordCount FROM Wormholes union all 
SELECT 'sqlite_stat1' AS TableName, COUNT(*) AS RecordCount FROM sqlite_stat1 union all 
SELECT 'sqlite_stat4' AS TableName, COUNT(*) AS RecordCount FROM sqlite_stat4 union all 
SELECT 'FCT_WreckComponents' AS TableName, COUNT(*) AS RecordCount FROM FCT_WreckComponents union all 
SELECT 'FCT_DamagedComponent' AS TableName, COUNT(*) AS RecordCount FROM FCT_DamagedComponent union all 
SELECT 'Formation' AS TableName, COUNT(*) AS RecordCount FROM Formation union all 
SELECT 'FCT_IndustrialProjects' AS TableName, COUNT(*) AS RecordCount FROM FCT_IndustrialProjects union all 
SELECT 'FCT_LagrangePoint' AS TableName, COUNT(*) AS RecordCount FROM FCT_LagrangePoint union all 
SELECT 'FCT_Lifepods' AS TableName, COUNT(*) AS RecordCount FROM FCT_Lifepods union all 
SELECT 'FCT_MassDriverPackets' AS TableName, COUNT(*) AS RecordCount FROM FCT_MassDriverPackets union all 
SELECT 'MissileSeries' AS TableName, COUNT(*) AS RecordCount FROM MissileSeries union all 
SELECT 'FCT_PopComponent' AS TableName, COUNT(*) AS RecordCount FROM FCT_PopComponent union all 
SELECT 'FCT_SectorCommand' AS TableName, COUNT(*) AS RecordCount FROM FCT_SectorCommand union all 
SELECT 'FCT_SystemBodyName' AS TableName, COUNT(*) AS RecordCount FROM FCT_SystemBodyName union all 
SELECT 'FCT_SurveyLocation' AS TableName, COUNT(*) AS RecordCount FROM FCT_SurveyLocation union all 
SELECT 'FCT_ClassMaterials' AS TableName, COUNT(*) AS RecordCount FROM FCT_ClassMaterials union all 
SELECT 'FCT_RaceSurveyLocation' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceSurveyLocation union all 
SELECT 'FCT_WreckTech' AS TableName, COUNT(*) AS RecordCount FROM FCT_WreckTech union all 
SELECT 'FCT_AtmosphericGas' AS TableName, COUNT(*) AS RecordCount FROM FCT_AtmosphericGas union all 
SELECT 'FCT_PopulationWeapon' AS TableName, COUNT(*) AS RecordCount FROM FCT_PopulationWeapon union all 
SELECT 'FCT_ShipWeapon' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipWeapon union all 
SELECT 'FCT_ClassOrdnanceTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_ClassOrdnanceTemplate union all 
SELECT 'FCT_ClassComponent' AS TableName, COUNT(*) AS RecordCount FROM FCT_ClassComponent union all 
SELECT 'FCT_ClassSC' AS TableName, COUNT(*) AS RecordCount FROM FCT_ClassSC union all 
SELECT 'FCT_FleetHistory' AS TableName, COUNT(*) AS RecordCount FROM FCT_FleetHistory union all 
SELECT 'FCT_ShipHistory' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipHistory union all 
SELECT 'FCT_WealthData' AS TableName, COUNT(*) AS RecordCount FROM FCT_WealthData union all 
SELECT 'FCT_ResearchQueue' AS TableName, COUNT(*) AS RecordCount FROM FCT_ResearchQueue union all 
SELECT 'FCT_AlienRaceSpecies' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienRaceSpecies union all 
SELECT 'FCT_RaceTech' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceTech union all 
SELECT 'FCT_EventColour' AS TableName, COUNT(*) AS RecordCount FROM FCT_EventColour union all 
SELECT 'FCT_SystemBodySurveys' AS TableName, COUNT(*) AS RecordCount FROM FCT_SystemBodySurveys union all 
SELECT 'DIM_SystemAge' AS TableName, COUNT(*) AS RecordCount FROM DIM_SystemAge union all 
SELECT 'DIM_SystemAbundance' AS TableName, COUNT(*) AS RecordCount FROM DIM_SystemAbundance union all 
SELECT 'DIM_NamingThemeTypes' AS TableName, COUNT(*) AS RecordCount FROM DIM_NamingThemeTypes union all 
SELECT 'DIM_EmpireTitles' AS TableName, COUNT(*) AS RecordCount FROM DIM_EmpireTitles union all 
SELECT 'DIM_Gases' AS TableName, COUNT(*) AS RecordCount FROM DIM_Gases union all 
SELECT 'DIM_RankThemeTypes' AS TableName, COUNT(*) AS RecordCount FROM DIM_RankThemeTypes union all 
SELECT 'DIM_RankThemes' AS TableName, COUNT(*) AS RecordCount FROM DIM_RankThemes union all 
SELECT 'FCT_Ranks' AS TableName, COUNT(*) AS RecordCount FROM FCT_Ranks union all 
SELECT 'DIM_CommanderNames' AS TableName, COUNT(*) AS RecordCount FROM DIM_CommanderNames union all 
SELECT 'FCT_CommanderHistory' AS TableName, COUNT(*) AS RecordCount FROM FCT_CommanderHistory union all 
SELECT 'FCT_MissileGeoSurvey' AS TableName, COUNT(*) AS RecordCount FROM FCT_MissileGeoSurvey union all 
SELECT 'FCT_WeaponRecharge' AS TableName, COUNT(*) AS RecordCount FROM FCT_WeaponRecharge union all 
SELECT 'FCT_WeaponAssignment' AS TableName, COUNT(*) AS RecordCount FROM FCT_WeaponAssignment union all 
SELECT 'FCT_MissileAssignment' AS TableName, COUNT(*) AS RecordCount FROM FCT_MissileAssignment union all 
SELECT 'FCT_ECCMAssignment' AS TableName, COUNT(*) AS RecordCount FROM FCT_ECCMAssignment union all 
SELECT 'FCT_CommanderBonuses' AS TableName, COUNT(*) AS RecordCount FROM FCT_CommanderBonuses union all 
SELECT 'DIM_NavalAdminCommandType' AS TableName, COUNT(*) AS RecordCount FROM DIM_NavalAdminCommandType union all 
SELECT 'FCT_PopulationInstallations' AS TableName, COUNT(*) AS RecordCount FROM FCT_PopulationInstallations union all 
SELECT 'FCT_RuinRace' AS TableName, COUNT(*) AS RecordCount FROM FCT_RuinRace union all 
SELECT 'DIM_CommanderBonusType' AS TableName, COUNT(*) AS RecordCount FROM DIM_CommanderBonusType union all 
SELECT 'FCT_Survivors' AS TableName, COUNT(*) AS RecordCount FROM FCT_Survivors union all 
SELECT 'DIM_AssignmentTypeFilter' AS TableName, COUNT(*) AS RecordCount FROM DIM_AssignmentTypeFilter union all 
SELECT 'FCT_KnownSpecies' AS TableName, COUNT(*) AS RecordCount FROM FCT_KnownSpecies union all 
SELECT 'FCT_GroundUnitCapability' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitCapability union all 
SELECT 'FCT_ShippingWealthData' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShippingWealthData union all 
SELECT 'FCT_ShipTechData' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipTechData union all 
SELECT 'FCT_AlienClassTech' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienClassTech union all 
SELECT 'FCT_MapLabel' AS TableName, COUNT(*) AS RecordCount FROM FCT_MapLabel union all 
SELECT 'FCT_MineralDeposit' AS TableName, COUNT(*) AS RecordCount FROM FCT_MineralDeposit union all 
SELECT 'FCT_CommanderTraits' AS TableName, COUNT(*) AS RecordCount FROM FCT_CommanderTraits union all 
SELECT 'FCT_ArmourDamage' AS TableName, COUNT(*) AS RecordCount FROM FCT_ArmourDamage union all 
SELECT 'DIM_SolSystemBodies' AS TableName, COUNT(*) AS RecordCount FROM DIM_SolSystemBodies union all 
SELECT 'FCT_GroundUnitFormationElementTemplates' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitFormationElementTemplates union all 
SELECT 'FCT_TechProgressionRace' AS TableName, COUNT(*) AS RecordCount FROM FCT_TechProgressionRace union all 
SELECT 'FCT_HideEvents' AS TableName, COUNT(*) AS RecordCount FROM FCT_HideEvents union all 
SELECT 'FCT_DamageControlQueue' AS TableName, COUNT(*) AS RecordCount FROM FCT_DamageControlQueue union all 
SELECT 'FCT_ShippingLines' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShippingLines union all 
SELECT 'DIM_GroundUnitArmour' AS TableName, COUNT(*) AS RecordCount FROM DIM_GroundUnitArmour union all 
SELECT 'DIM_GroundUnitBaseType' AS TableName, COUNT(*) AS RecordCount FROM DIM_GroundUnitBaseType union all 
SELECT 'DIM_TraitsList' AS TableName, COUNT(*) AS RecordCount FROM DIM_TraitsList union all 
SELECT 'FCT_AlienRaceSensor' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienRaceSensor union all 
SELECT 'FCT_ElementRecharge' AS TableName, COUNT(*) AS RecordCount FROM FCT_ElementRecharge union all 
SELECT 'FCT_GroundUnitFormationElement' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitFormationElement union all 
SELECT 'FCT_STODetected' AS TableName, COUNT(*) AS RecordCount FROM FCT_STODetected union all 
SELECT 'FCT_PopInstallationDemand' AS TableName, COUNT(*) AS RecordCount FROM FCT_PopInstallationDemand union all 
SELECT 'FCT_AlienClassWeapon' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienClassWeapon union all 
SELECT 'FCT_AlienClassSensor' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienClassSensor union all 
SELECT 'FCT_AcidAttack' AS TableName, COUNT(*) AS RecordCount FROM FCT_AcidAttack union all 
SELECT 'FCT_SwarmResearch' AS TableName, COUNT(*) AS RecordCount FROM FCT_SwarmResearch union all 
SELECT 'DIM_AutomatedGroundTemplateElements' AS TableName, COUNT(*) AS RecordCount FROM DIM_AutomatedGroundTemplateElements union all 
SELECT 'DIM_GroundUnitCapability' AS TableName, COUNT(*) AS RecordCount FROM DIM_GroundUnitCapability union all 
SELECT 'DIM_TradeGoods' AS TableName, COUNT(*) AS RecordCount FROM DIM_TradeGoods union all 
SELECT 'DIM_PlanetaryInstallation' AS TableName, COUNT(*) AS RecordCount FROM DIM_PlanetaryInstallation union all 
SELECT 'FCT_OrderTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_OrderTemplate union all 
SELECT 'FCT_RaceNameThemes' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceNameThemes union all 
SELECT 'FCT_MedalConditionAssignment' AS TableName, COUNT(*) AS RecordCount FROM FCT_MedalConditionAssignment union all 
SELECT 'FCT_CommanderMeasurement' AS TableName, COUNT(*) AS RecordCount FROM FCT_CommanderMeasurement union all 
SELECT 'FCT_CommanderMedal' AS TableName, COUNT(*) AS RecordCount FROM FCT_CommanderMedal union all 
SELECT 'FCT_GameLog' AS TableName, COUNT(*) AS RecordCount FROM FCT_GameLog union all 
SELECT 'FCT_ShipOrdnanceTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipOrdnanceTemplate union all 
SELECT 'FCT_AlienGroundUnitClass' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienGroundUnitClass union all 
SELECT 'DIM_DesignPhilosophyGroundForceDeployments' AS TableName, COUNT(*) AS RecordCount FROM DIM_DesignPhilosophyGroundForceDeployments union all 
SELECT 'FCT_ShipCargo' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipCargo union all 
SELECT 'DIM_OperationalGroup' AS TableName, COUNT(*) AS RecordCount FROM DIM_OperationalGroup union all 
SELECT 'FCT_RaceGroundCombat' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceGroundCombat union all 
SELECT 'FCT_AlienRaceSystemStatus' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienRaceSystemStatus union all 
SELECT 'DIM_ResearchField' AS TableName, COUNT(*) AS RecordCount FROM DIM_ResearchField union all 
SELECT 'DIM_CommanderNameTheme' AS TableName, COUNT(*) AS RecordCount FROM DIM_CommanderNameTheme union all 
SELECT 'DIM_MedalCondition' AS TableName, COUNT(*) AS RecordCount FROM DIM_MedalCondition union all 
SELECT 'FCT_ShipMeasurementOld' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipMeasurementOld union all 
SELECT 'FCT_BannedBodies' AS TableName, COUNT(*) AS RecordCount FROM FCT_BannedBodies union all 
SELECT 'FCT_RaceMedals' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceMedals union all 
SELECT 'FCT_WindowPosition' AS TableName, COUNT(*) AS RecordCount FROM FCT_WindowPosition union all 
SELECT 'DIM_EventType' AS TableName, COUNT(*) AS RecordCount FROM DIM_EventType union all 
SELECT 'DIM_AutomatedGroundTemplateDesign' AS TableName, COUNT(*) AS RecordCount FROM DIM_AutomatedGroundTemplateDesign union all 
SELECT 'FCT_PopTradeBalance' AS TableName, COUNT(*) AS RecordCount FROM FCT_PopTradeBalance union all 
SELECT 'DefaultEventColour' AS TableName, COUNT(*) AS RecordCount FROM DefaultEventColour union all 
SELECT 'FCT_MoveOrders' AS TableName, COUNT(*) AS RecordCount FROM FCT_MoveOrders union all 
SELECT 'FCT_MoveOrderTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_MoveOrderTemplate union all 
SELECT 'FCT_TechSystem' AS TableName, COUNT(*) AS RecordCount FROM FCT_TechSystem union all 
SELECT 'FCT_AetherRift' AS TableName, COUNT(*) AS RecordCount FROM FCT_AetherRift union all 
SELECT 'FCT_AncientConstruct' AS TableName, COUNT(*) AS RecordCount FROM FCT_AncientConstruct union all 
SELECT 'FCT_RaceOperationalGroupElements' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceOperationalGroupElements union all 
SELECT 'FCT_ResearchProject' AS TableName, COUNT(*) AS RecordCount FROM FCT_ResearchProject union all 
SELECT 'FCT_SubFleets' AS TableName, COUNT(*) AS RecordCount FROM FCT_SubFleets union all 
SELECT 'FCT_GroundUnitSeries' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitSeries union all 
SELECT 'FCT_GroundUnitSeriesClass' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitSeriesClass union all 
SELECT 'FCT_PausedResearch' AS TableName, COUNT(*) AS RecordCount FROM FCT_PausedResearch union all 
SELECT 'FCT_ShipMeasurement' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipMeasurement union all 
SELECT 'DIM_Constellation' AS TableName, COUNT(*) AS RecordCount FROM DIM_Constellation union all 
SELECT 'DIM_DesignPhilosophyTechProgression' AS TableName, COUNT(*) AS RecordCount FROM DIM_DesignPhilosophyTechProgression union all 
SELECT 'FCT_AlienSystem' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienSystem union all 
SELECT 'FCT_RaceSysSurvey' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceSysSurvey union all 
SELECT 'FCT_Contacts' AS TableName, COUNT(*) AS RecordCount FROM FCT_Contacts union all 
SELECT 'FCT_Star' AS TableName, COUNT(*) AS RecordCount FROM FCT_Star union all 
SELECT 'FCT_RaceJumpPointSurvey' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceJumpPointSurvey union all 
SELECT 'DIM_PlanetaryTerrain' AS TableName, COUNT(*) AS RecordCount FROM DIM_PlanetaryTerrain union all 
SELECT 'FCT_HullNumber' AS TableName, COUNT(*) AS RecordCount FROM FCT_HullNumber union all 
SELECT 'FCT_Squadron' AS TableName, COUNT(*) AS RecordCount FROM FCT_Squadron union all 
SELECT 'FCT_SystemBody' AS TableName, COUNT(*) AS RecordCount FROM FCT_SystemBody union all 
SELECT 'FCT_WealthHistory' AS TableName, COUNT(*) AS RecordCount FROM FCT_WealthHistory union all 
SELECT 'DIM_StellarType' AS TableName, COUNT(*) AS RecordCount FROM DIM_StellarType union all 
SELECT 'FCT_System' AS TableName, COUNT(*) AS RecordCount FROM FCT_System union all 
SELECT 'FCT_GroundUnitClass' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitClass union all 
SELECT 'FCT_GroundUnitTrainingQueue' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitTrainingQueue union all 
SELECT 'FCT_GroundUnitTraining' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitTraining union all 
SELECT 'DIM_MoveAction' AS TableName, COUNT(*) AS RecordCount FROM DIM_MoveAction union all 
SELECT 'DIM_GroundComponentType' AS TableName, COUNT(*) AS RecordCount FROM DIM_GroundComponentType union all 
SELECT 'FCT_ClassGroundTemplates' AS TableName, COUNT(*) AS RecordCount FROM FCT_ClassGroundTemplates union all 
SELECT 'FCT_AlienClass' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienClass union all 
SELECT 'FCT_Missile' AS TableName, COUNT(*) AS RecordCount FROM FCT_Missile union all 
SELECT 'FCT_FireControlAssignment' AS TableName, COUNT(*) AS RecordCount FROM FCT_FireControlAssignment union all 
SELECT 'FCT_DesignPhilosophyTechProgressionCategories' AS TableName, COUNT(*) AS RecordCount FROM FCT_DesignPhilosophyTechProgressionCategories union all 
SELECT 'DIM_OperationalGroupElement' AS TableName, COUNT(*) AS RecordCount FROM DIM_OperationalGroupElement union all 
SELECT 'FCT_DecoyAssignment' AS TableName, COUNT(*) AS RecordCount FROM FCT_DecoyAssignment union all 
SELECT 'FCT_ClassComponentTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_ClassComponentTemplate union all 
SELECT 'FCT_ShipClassTemplate_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipClassTemplate_old union all 
SELECT 'FCT_AetherGates' AS TableName, COUNT(*) AS RecordCount FROM FCT_AetherGates union all 
SELECT 'FCT_ShipComponentTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipComponentTemplate union all 
SELECT 'DIM_TechType' AS TableName, COUNT(*) AS RecordCount FROM DIM_TechType union all 
SELECT 'DIM_ResearchCategories' AS TableName, COUNT(*) AS RecordCount FROM DIM_ResearchCategories union all 
SELECT 'DIM_KnownSystems_Old' AS TableName, COUNT(*) AS RecordCount FROM DIM_KnownSystems_Old union all 
SELECT 'DIM_KnownSystems' AS TableName, COUNT(*) AS RecordCount FROM DIM_KnownSystems union all 
SELECT 'FCT_GroundUnitFormationTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitFormationTemplate union all 
SELECT 'FCT_OrganizationNode' AS TableName, COUNT(*) AS RecordCount FROM FCT_OrganizationNode union all 
SELECT 'FCT_Population_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_Population_old union all 
SELECT 'FCT_ShipyardTask' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipyardTask union all 
SELECT 'FCT_Shipyard' AS TableName, COUNT(*) AS RecordCount FROM FCT_Shipyard union all 
SELECT 'FCT_MissileType' AS TableName, COUNT(*) AS RecordCount FROM FCT_MissileType union all 
SELECT 'FCT_MissileSalvo' AS TableName, COUNT(*) AS RecordCount FROM FCT_MissileSalvo union all 
SELECT 'FCT_ShipDesignComponents' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipDesignComponents union all 
SELECT 'FCT_EligibleProjects' AS TableName, COUNT(*) AS RecordCount FROM FCT_EligibleProjects union all 
SELECT 'FCT_Prisoners' AS TableName, COUNT(*) AS RecordCount FROM FCT_Prisoners union all 
SELECT 'FCT_Commander' AS TableName, COUNT(*) AS RecordCount FROM FCT_Commander union all 
SELECT 'DIM_OperationalGroupProgression' AS TableName, COUNT(*) AS RecordCount FROM DIM_OperationalGroupProgression union all 
SELECT 'DIM_AutomatedClassDesign' AS TableName, COUNT(*) AS RecordCount FROM DIM_AutomatedClassDesign union all 
SELECT 'FCT_DesignPhilosophy_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_DesignPhilosophy_old union all 
SELECT 'DIM_Ruin' AS TableName, COUNT(*) AS RecordCount FROM DIM_Ruin union all 
SELECT 'FCT_PrecursorTombGroup' AS TableName, COUNT(*) AS RecordCount FROM FCT_PrecursorTombGroup union all 
SELECT 'FCT_AlienPopulation' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienPopulation union all 
SELECT 'FCT_GroundUnitFormation' AS TableName, COUNT(*) AS RecordCount FROM FCT_GroundUnitFormation union all 
SELECT 'FCT_Ship_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_Ship_old union all 
SELECT 'FCT_AlienShip' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienShip union all 
SELECT 'FCT_Wrecks' AS TableName, COUNT(*) AS RecordCount FROM FCT_Wrecks union all 
SELECT 'DIM_ClassSummaryType' AS TableName, COUNT(*) AS RecordCount FROM DIM_ClassSummaryType union all 
SELECT 'DIM_ComponentType' AS TableName, COUNT(*) AS RecordCount FROM DIM_ComponentType union all 
SELECT 'FCT_FleetStandingOrder' AS TableName, COUNT(*) AS RecordCount FROM FCT_FleetStandingOrder union all 
SELECT 'DIM_StandingOrders' AS TableName, COUNT(*) AS RecordCount FROM DIM_StandingOrders union all 
SELECT 'FCT_StandingOrderTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_StandingOrderTemplate union all 
SELECT 'FCT_Waypoint' AS TableName, COUNT(*) AS RecordCount FROM FCT_Waypoint union all 
SELECT 'FCT_StandingOrderTemplateOrder' AS TableName, COUNT(*) AS RecordCount FROM FCT_StandingOrderTemplateOrder union all 
SELECT 'FCT_NavalAdminCommand' AS TableName, COUNT(*) AS RecordCount FROM FCT_NavalAdminCommand union all 
SELECT 'FCT_ShipClass' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipClass union all 
SELECT 'FCT_Fleet_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_Fleet_old union all 
SELECT 'FCT_RaceMineralData' AS TableName, COUNT(*) AS RecordCount FROM FCT_RaceMineralData union all 
SELECT 'DIM_MineralDataType' AS TableName, COUNT(*) AS RecordCount FROM DIM_MineralDataType union all 
SELECT 'FCT_FleetConditionalOrder' AS TableName, COUNT(*) AS RecordCount FROM FCT_FleetConditionalOrder union all 
SELECT 'FCT_AlienRace' AS TableName, COUNT(*) AS RecordCount FROM FCT_AlienRace union all 
SELECT 'FCT_Race_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_Race_old union all 
SELECT 'FCT_Species' AS TableName, COUNT(*) AS RecordCount FROM FCT_Species union all 
SELECT 'FCT_Game_old' AS TableName, COUNT(*) AS RecordCount FROM FCT_Game_old union all 
SELECT 'FCT_DesignPhilosophy' AS TableName, COUNT(*) AS RecordCount FROM FCT_DesignPhilosophy union all 
SELECT 'FCT_Fleet' AS TableName, COUNT(*) AS RecordCount FROM FCT_Fleet union all 
SELECT 'FCT_Game' AS TableName, COUNT(*) AS RecordCount FROM FCT_Game union all 
SELECT 'FCT_Population' AS TableName, COUNT(*) AS RecordCount FROM FCT_Population union all 
SELECT 'FCT_Race' AS TableName, COUNT(*) AS RecordCount FROM FCT_Race union all 
SELECT 'FCT_Ship' AS TableName, COUNT(*) AS RecordCount FROM FCT_Ship union all 
SELECT 'FCT_ShipClassTemplate' AS TableName, COUNT(*) AS RecordCount FROM FCT_ShipClassTemplate --union all 
) as x order by RecordCount desc
-- */