DELETE	FROM	sqlite_stat1 WHERE rowid=7487;
DELETE	FROM	sqlite_stat1 WHERE rowid=7552;
DELETE	FROM	sqlite_stat1 WHERE rowid=7556;
UPDATE	FCT_Race SET SpaceStationPic='SpaceStation017.png' WHERE RaceID=194;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24990;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24993;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24994;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24995;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24996;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24997;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24998;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=24999;	
UPDATE	FCT_ShipDesignComponents SET SingleSystemOnly=1 WHERE SDComponentID=33215;	
UPDATE	FCT_TechSystem SET AdditionalInfo=0.15 WHERE TechSystemID=26602;	
UPDATE	FCT_TechSystem SET AdditionalInfo=0.3 WHERE TechSystemID=26584;	
UPDATE	FCT_TechSystem SET AdditionalInfo=0.4, AdditionalInfo3=0.25 WHERE TechSystemID=26237;	
UPDATE	FCT_TechSystem SET AdditionalInfo=0.6, AdditionalInfo3=0.45 WHERE TechSystemID=26236;	
UPDATE	FCT_TechSystem SET AdditionalInfo3=0.7 WHERE TechSystemID=26235;	
INSERT INTO	sqlite_stat1(rowid,tbl,idx,stat) VALUES(7608,'FCT_TechSystem',NULL,'1890');	
INSERT INTO	sqlite_stat1(rowid,tbl,idx,stat) VALUES(7609,'FCT_ShipDesignComponents',NULL,'883');	
INSERT INTO	sqlite_stat1(rowid,tbl,idx,stat) VALUES(7610,'FCT_Race',NULL,'6');	
