--create view vw_empireMining as

          select  'Duranium' as Mineral, sum(_pop.Duranium) as Stock, sum(_pop.Duranium) - sum(_pop.LastDuranium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Neutronium' as Mineral, sum(_pop.Neutronium) as Stock, sum(_pop.Neutronium) - sum(_pop.LastNeutronium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Corbomite' as Mineral, sum(_pop.Corbomite) as Stock, sum(_pop.Corbomite) - sum(_pop.LastCorbomite) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Tritanium' as Mineral, sum(_pop.Tritanium) as Stock, sum(_pop.Tritanium) - sum(_pop.LastTritanium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Boronide' as Mineral, sum(_pop.Boronide) as Stock, sum(_pop.Boronide) - sum(_pop.LastBoronide) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Mercassium' as Mineral, sum(_pop.Mercassium) as Stock, sum(_pop.Mercassium) - sum(_pop.LastMercassium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Vendarite' as Mineral, sum(_pop.Vendarite) as Stock, sum(_pop.Vendarite) - sum(_pop.LastVendarite) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Sorium' as Mineral, sum(_pop.Sorium) as Stock, sum(_pop.Sorium) - sum(_pop.LastSorium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Uridium' as Mineral, sum(_pop.Uridium) as Stock, sum(_pop.Uridium) - sum(_pop.LastUridium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Corundium' as Mineral, sum(_pop.Corundium) as Stock, sum(_pop.Corundium) - sum(_pop.LastCorundium) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
union all select  'Gallicite' as Mineral, sum(_pop.Gallicite) as Stock, sum(_pop.Gallicite) - sum(_pop.LastGallicite) as Change	FROM FCT_Population as _pop inner JOIN (select max(RaceID) as RaceID from FCT_Race where NPR = 0) as CurrentRace on CurrentRace.RaceID = _pop.RaceID
